name : "test map"
layout >
  zones >
    zone0 >
      x : f-500.000000
      y : f10.000000
      w : f2000.000000
      h : f200.000000
  transitions >
  start >
    x : f48.000000
    y : f93.000000
background >
  sky >
    path : "assets/breach/bg.png"
    parallax : f0.000000
    x : f0.000000
    y : f0.000000
  clouds >
    path : "assets/breach/clouds.png"
    parallax : f0.500000
    x : f0.000000
    y : f0.000000
  horizon >
    path : "assets/breach/mid.png"
    parallax : f0.700000
    x : f0.000000
    y : f0.000000
  ground >
    path : "assets/breach/foreground.png"
    parallax : f1.000000
    x : f0.000000
    y : f0.000000
